export const INIT_USER_REQUESTED = 'INIT_USER_REQUESTED';
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGOUT_USER_REQUESTED = 'LOGOUT_USER_REQUESTED';
export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED';
export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const RESET_USER_DATA = 'RESET_USER_DATA';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_USER_IS_LOADING = 'SET_USER_IS_LOADING';
export const SET_USER_IS_AUTHENTICATING = 'SET_USER_IS_AUTHENTICATING';
