export const SET_TASKS_LIST = 'SET_TASKS_LIST';
export const PUSH_TASKS_LIST = 'PUSH_TASKS_LIST';
export const RESET_TASKS_LIST = 'RESET_TASKS_LIST';
export const SET_IS_LOADING = 'SET_TASKS_IS_LOADING';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';

export const ADD_TASK_REQUESTED = 'ADD_TASK_REQUESTED';
export const GET_TASK_REQUESTED = 'GET_TASK_REQUESTED';
export const UPDATE_TASK_REQUESTED = 'UPDATE_TASK_REQUESTED';
export const REMOVE_TASK_REQUESTED = 'REMOVE_TASK_REQUESTED';
export const GET_TASK_LIST_REQUESTED = 'GET_TASK_LIST_REQUESTED';
